### ISSUE TITLE
Registration Stalls in T-Pose...

### ISSUE THREAD

**Issue by merekemess** [fg-uulm/fusionkit#1]
2 sensors are loaded and data is flowing as i can view myself in the 3d viewer (as 2 different skeletons). However the registration wizard does nothing except state that its is waiting for t-pose...

What can i do to fix this

Details:
3 windows 10 laptops
2 running sensor servers with 1 kinect v2 each, with no firewall, appears smooth and pretty.
1 running studio, also running the software smoothly
1 router running all 3 machines, lan.
All software is running as admin.

**Comment by fg-uulm** [comment]
Hi tallywackereb,

thanks for trying out our software. Regarding your problem - did you select a main sensor before actually doing the T-Pose (assuming you did one already)?
You can select one by right-clicking it in the list and selecting "Assign as main sensor" (normally this should happen automatically, however). The selected sensor should be highlighted then in the list as well as in the 3D view.
Also, here's (http://i.stack.imgur.com/FKRLc.jpg) what the T-Pose should actually look like when you do it in front of the sensor, just stay that way for some seconds and registration should start...

-- Flo

**Comment by merekemess** [comment]
Very helpful. Sb...

**Comment by merekemess** [comment]
This worked perfectly.

**Comment by fg-uulm** [comment]
Thanks for the feedback! We'll add that information to the Getting Started guide asap then.
